<a href="https://colab.research.google.com/github/okada-t-rafael/time_series_data_analysis/blob/master/32_TS_Pandas_Time_Shifting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import files
files.upload()

Saving starbucks.csv to starbucks.csv

{'starbucks.csv': b'Date,Close,Volume\n2015-01-02,38.0061,6906098\n2015-01-05,37.2781,11623796\n2015-01-06,36.9748,7664340\n2015-01-07,37.8848,9732554\n2015-01-08,38.4961,13170548\n2015-01-09,37.2361,27556706\n2015-01-12,37.4415,10021486\n2015-01-13,37.7401,11040702\n2015-01-14,37.5301,9295084\n2015-01-15,37.1381,8126602\n2015-01-16,37.6188,9015502\n2015-01-20,37.9058,10738304\n2015-01-21,37.9361,10844182\n2015-01-22,38.6128,23913056\n2015-01-23,41.1702,38107194\n2015-01-26,41.1235,14098574\n2015-01-27,41.2262,10995808\n2015-01-28,40.8645,11963202\n2015-01-29,41.5575,12475860\n2015-01-30,40.8482,10070456\n2015-02-02,41.0629,13638832\n2015-02-03,41.4469,9252426\n2015-02-04,41.5453,11496698\n2015-02-05,41.9856,7598672\n2015-02-06,41.6858,7835332\n2015-02-09,41.6015,6911614\n2015-02-10,42.7069,12469500\n2015-02-11,42.5242,6466910\n2015-02-12,43.009,7197558\n2015-02-13,42.8942,6109522\n2015-02-17,43.105,6386900\n2015-02-18,43.5593,6541986\n2015-02-19,43.639,6109176\n2015-02-20,43.7982,6462662\n2015-02-23,43.831,5854572\n2015-02-24,43.7701,6337888\n2015-02-25,44.1495,8120660\n2015-02-26,44.2853,6816352\n2015-02-27,43.7865,8658404\n2015-03-02,44.1331,7947018\n2015-03-03,44.0277,7578374\n2015-03-04,43.5874,7774534\n2015-03-05,43.8544,5848750\n2015-03-06,43.1917,6814414\n2015-03-09,43.5781,5984880\n2015-03-10,43.1753,6076984\n2015-03-11,42.8193,8185894\n2015-03-12,43.7373,7295344\n2015-03-13,43.6952,5835252\n2015-03-16,44.0488,6772606\n2015-03-17,44.208,5508796\n2015-03-18,44.8895,15429928\n2015-03-19,45.7888,22020618\n2015-03-20,45.6483,17360612\n2015-03-23,45.6062,7985986\n2015-03-24,45.8614,7718488\n2015-03-25,44.8567,9907170\n2015-03-26,44.5336,10344304\n2015-03-27,44.5289,7993350\n2015-03-30,44.9551,6830270\n2015-03-31,44.3556,8717754\n2015-04-01,43.5687,14125350\n2015-04-02,44.2104,8863018\n2015-04-06,44.2713,6058894\n2015-04-07,44.0605,5354670\n2015-04-08,44.6038,6827888\n2015-04-09,44.927,7109621\n2015-04-10,45.1237,6643106\n2015-04-13,45.4329,8171030\n2015-04-14,45.2455,5952424\n2015-04-15,45.0956,5162169\n2015-04-16,45.194,5312499\n2015-04-17,44.6085,7539865\n2015-04-20,44.9364,4868425\n2015-04-21,45.3111,6213360\n2015-04-22,45.2783,7248119\n2015-04-23,46.304,15866051\n2015-04-24,48.5616,22284881\n2015-04-27,47.653,11222608\n2015-04-28,47.4094,8882901\n2015-04-29,47.4469,7161992\n2015-04-30,46.4446,8492048\n2015-05-01,47.1097,5916509\n2015-05-04,47.2549,7493420\n2015-05-05,46.4279,10691207\n2015-05-06,45.9815,8033489\n2015-05-07,46.3762,5681417\n2015-05-08,46.7803,6039840\n2015-05-11,46.5172,5047180\n2015-05-12,46.7145,5868552\n2015-05-13,46.6017,4927094\n2015-05-14,47.5086,7339742\n2015-05-15,47.7388,6016694\n2015-05-18,48.0959,8999761\n2015-05-19,48.3215,6976052\n2015-05-20,47.955,5644662\n2015-05-21,48.2369,5084042\n2015-05-22,48.3779,5857672\n2015-05-26,47.7764,7369923\n2015-05-27,48.4812,6213573\n2015-05-28,48.688,5874382\n2015-05-29,48.8289,9399112\n2015-06-01,49.0733,7075082\n2015-06-02,48.6128,7877799\n2015-06-03,48.9793,5522702\n2015-06-04,48.6034,6230805\n2015-06-05,49.0451,7123248\n2015-06-08,48.4248,6320181\n2015-06-09,48.4342,5034038\n2015-06-10,49.5149,8003611\n2015-06-11,49.327,6030167\n2015-06-12,49.4586,5236747\n2015-06-15,49.1203,5554964\n2015-06-16,49.7734,6106529\n2015-06-17,50.0318,6735294\n2015-06-18,50.8494,10712142\n2015-06-19,50.6802,10609714\n2015-06-22,50.652,7100665\n2015-06-23,50.8541,5679984\n2015-06-24,50.4735,5524969\n2015-06-25,50.8118,5389863\n2015-06-26,51.3286,6637183\n2015-06-29,50.3231,6534077\n2015-06-30,50.3842,9793969\n2015-07-01,50.6426,6107698\n2015-07-02,50.9715,5684667\n2015-07-06,51.0326,5396439\n2015-07-07,51.0984,9462256\n2015-07-08,50.1728,8139303\n2015-07-09,50.793,7681013\n2015-07-10,51.2817,8087800\n2015-07-13,52.3436,7477170\n2015-07-14,52.3905,7028025\n2015-07-15,52.0053,8212573\n2015-07-16,52.3812,7305520\n2015-07-17,52.3342,8715431\n2015-07-20,52.8228,8029646\n2015-07-21,52.8134,6717452\n2015-07-22,53.2739,6876059\n2015-07-23,53.1517,12439229\n2015-07-24,53.8377,14559687\n2015-07-27,53.5464,8993523\n2015-07-28,53.6968,8689215\n2015-07-29,54.0445,8470512\n2015-07-30,54.5613,7337948\n2015-07-31,54.4392,6519528\n2015-08-03,54.6835,7664002\n2015-08-04,55.3149,9113083\n2015-08-05,55.607,7349063\n2015-08-06,53.9297,11064470\n2015-08-07,53.9014,7781995\n2015-08-10,53.025,12029150\n2015-08-11,53.1004,8062553\n2015-08-12,53.1287,10075571\n2015-08-13,53.5716,6731474\n2015-08-14,53.8072,4803903\n2015-08-17,54.4103,5768362\n2015-08-18,54.4951,5575441\n2015-08-19,54.2689,6044193\n2015-08-20,52.5916,7470885\n2015-08-21,49.7928,20211503\n2015-08-24,47.437,27158813\n2015-08-25,48.1438,19659002\n2015-08-26,50.8482,15517591\n2015-08-27,52.7235,15987923\n2015-08-28,52.4219,7584826\n2015-08-31,51.555,7971204\n2015-09-01,50.4148,13424932\n2015-09-02,52.0733,9891071\n2015-09-03,51.5361,7968868\n2015-09-04,51.1498,6994267\n2015-09-08,52.0262,8051710\n2015-09-09,51.5361,8406656\n2015-09-10,52.1769,8924778\n2015-09-11,53.27,8363110\n2015-09-14,53.0439,5464463\n2015-09-15,53.6281,6741341\n2015-09-16,53.9579,6593362\n2015-09-17,53.9768,7525349\n2015-09-18,53.5622,16268035\n2015-09-21,54.2218,6220131\n2015-09-22,53.826,8585093\n2015-09-23,54.4574,6829205\n2015-09-24,55.0039,10027330\n2015-09-25,54.6458,10627026\n2015-09-28,52.5539,11548114\n2015-09-29,52.5068,9392065\n2015-09-30,53.5622,9799610\n2015-10-01,54.1653,8497124\n2015-10-02,54.7307,9036765\n2015-10-05,55.6353,8198998\n2015-10-06,55.3055,5642949\n2015-10-07,55.3903,8138313\n2015-10-08,56.0311,6834836\n2015-10-09,56.6059,7969884\n2015-10-12,57.0488,6430301\n2015-10-13,56.6907,6262774\n2015-10-14,55.428,8365604\n2015-10-15,56.2478,9745919\n2015-10-16,56.474,12860812\n2015-10-19,57.454,8117213\n2015-10-20,57.3692,6089097\n2015-10-21,57.0394,6063923\n2015-10-22,57.944,9182031\n2015-10-23,58.9994,8205994\n2015-10-26,59.7721,9751716\n2015-10-27,59.0937,8973243\n2015-10-28,59.8475,9627260\n2015-10-29,58.8958,14839093\n2015-10-30,58.9617,16822302\n2015-11-02,58.6508,8547237\n2015-11-03,59.1785,8847718\n2015-11-04,58.3869,9085091\n2015-11-05,58.6884,6144979\n2015-11-06,58.3963,6616305\n2015-11-09,57.9898,6838326\n2015-11-10,58.7839,6689040\n2015-11-11,58.4908,4437315\n2015-11-12,57.7345,6793779\n2015-11-13,56.4772,8821593\n2015-11-16,57.3658,8096603\n2015-11-17,57.2429,6695251\n2015-11-18,58.4247,7215255\n2015-11-19,58.1032,5154366\n2015-11-20,58.6043,8302476\n2015-11-23,59.2188,8493485\n2015-11-24,58.5759,7908223\n2015-11-25,58.7934,4549913\n2015-11-27,58.7839,2447902\n2015-11-30,58.0371,9863771\n2015-12-01,58.0182,10910838\n2015-12-02,57.8763,6587454\n2015-12-03,56.2976,12056103\n2015-12-04,58.3774,9100588\n2015-12-07,58.5097,5967809\n2015-12-08,58.765,6664947\n2015-12-09,57.8385,8541573\n2015-12-10,58.4908,6623896\n2015-12-11,56.5528,11489255\n2015-12-14,56.6473,13453719\n2015-12-15,56.7041,7842073\n2015-12-16,57.0539,9281835\n2015-12-17,56.2645,9079430\n2015-12-18,55.4183,18099462\n2015-12-21,56.2881,7187470\n2015-12-22,56.7135,6501424\n2015-12-23,57.0444,4510229\n2015-12-24,57.0255,2215418\n2015-12-28,56.9026,4437236\n2015-12-29,57.7913,5477335\n2015-12-30,57.4982,3973912\n2015-12-31,56.7513,4960875\n2016-01-04,55.078,13521544\n2016-01-05,55.4467,9617778\n2016-01-06,54.9551,8266322\n2016-01-07,53.5938,11140877\n2016-01-08,53.537,10427021\n2016-01-11,54.662,10757313\n2016-01-12,56.2125,12375826\n2016-01-13,54.7093,11303603\n2016-01-14,55.7587,11444106\n2016-01-15,54.8322,15246127\n2016-01-19,55.3522,12288950\n2016-01-20,53.8112,22786359\n2016-01-21,55.806,20888519\n2016-01-22,55.9383,32820193\n2016-01-25,54.5581,13554262\n2016-01-26,55.4089,8898100\n2016-01-27,54.4824,12491252\n2016-01-28,56.047,11832368\n2016-01-29,57.4509,13224438\n2016-02-01,58.0465,9529094\n2016-02-02,57.5675,9407352\n2016-02-03,56.4625,12254460\n2016-02-04,55.2864,13944926\n2016-02-05,51.6822,24529008\n2016-02-08,51.3503,21457492\n2016-02-09,51.6159,11605059\n2016-02-10,52.2988,11663942\n2016-02-11,52.0901,12106062\n2016-02-12,52.9817,8680205\n2016-02-16,53.5033,11594766\n2016-02-17,54.6604,11955188\n2016-02-18,54.025,8493953\n2016-02-19,54.6984,9033620\n2016-02-22,55.8366,8390689\n2016-02-23,55.4477,7064095\n2016-02-24,55.1157,10780882\n2016-02-25,55.7227,6262127\n2016-02-26,55.3339,7473374\n2016-02-29,55.2106,7645081\n2016-03-01,56.9463,9183562\n2016-03-02,56.491,8856392\n2016-03-03,55.9978,8262455\n2016-03-04,55.6753,8344773\n2016-03-07,55.0114,9204624\n2016-03-08,54.632,8127426\n2016-03-09,54.1293,9734589\n2016-03-10,54.5561,7023785\n2016-03-11,54.6225,15497560\n2016-03-14,55.6279,9053250\n2016-03-15,56.0357,7428469\n2016-03-16,56.5953,8069427\n2016-03-17,56.4815,7734658\n2016-03-18,56.6238,14313578\n2016-03-21,56.0547,6487185\n2016-03-22,56.3203,8246837\n2016-03-23,55.7986,5794495\n2016-03-24,55.3528,5948307\n2016-03-28,55.9219,5791603\n2016-03-29,56.4815,6031947\n2016-03-30,56.9178,5723499\n2016-03-31,56.6238,5622834\n2016-04-01,57.8758,9401126\n2016-04-04,57.1454,5799864\n2016-04-05,56.9463,4994792\n2016-04-06,57.6956,5667253\n2016-04-07,58.018,8239174\n2016-04-08,57.8947,5064894\n2016-04-11,57.762,6103358\n2016-04-12,56.4341,17565750\n2016-04-13,57.1075,9898527\n2016-04-14,57.0316,5157368\n2016-04-15,57.392,5965310\n2016-04-18,57.7525,7228573\n2016-04-19,57.762,7283570\n2016-04-20,57.762,5558770\n2016-04-21,57.5153,12799083\n2016-04-22,54.7079,29836693\n2016-04-25,54.7932,8428038\n2016-04-26,54.7458,8839067\n2016-04-27,53.9681,12390767\n2016-04-28,53.5128,9196560\n2016-04-29,53.3326,12133364\n2016-05-02,54.4044,8616189\n2016-05-03,53.5382,7854260\n2016-05-04,53.6715,6508507\n2016-05-05,53.5382,6215367\n2016-05-06,53.5954,6378690\n2016-05-09,53.9094,5976229\n2016-05-10,54.7185,7931185\n2016-05-11,53.5192,8118920\n2016-05-12,53.5858,6870281\n2016-05-13,53.129,5466041\n2016-05-16,52.853,9536192\n2016-05-17,52.2343,10530018\n2016-05-18,52.1581,7468496\n2016-05-19,51.9202,7582848\n2016-05-20,51.9868,8430783\n2016-05-23,51.9678,7352054\n2016-05-24,52.7673,7748697\n2016-05-25,52.4913,8126058\n2016-05-26,52.6245,9451708\n2016-05-27,52.4913,6631120\n2016-05-31,52.2438,12043976\n2016-06-01,52.1772,8761577\n2016-06-02,51.9868,8307488\n2016-06-03,51.9773,6649224\n2016-06-06,52.9101,9900917\n2016-06-07,52.634,7173072\n2016-06-08,52.5579,7623851\n2016-06-09,52.9005,5927854\n2016-06-10,52.22,8118651\n2016-06-13,52.3866,7928722\n2016-06-14,52.891,8036517\n2016-06-15,52.6816,7447317\n2016-06-16,52.853,7968033\n2016-06-17,52.6436,9503017\n2016-06-20,52.7102,7286681\n2016-06-21,53.1195,7445109\n2016-06-22,52.9291,7215411\n2016-06-23,53.424,5569431\n2016-06-24,52.0439,14654672\n2016-06-27,51.1017,11650798\n2016-06-28,52.2057,8416950\n2016-06-29,54.0046,11103787\n2016-06-30,54.3663,10215193\n2016-07-01,54.2426,8330308\n2016-07-05,54.0332,7274208\n2016-07-06,54.0141,8474188\n2016-07-07,54.1664,6813347\n2016-07-08,53.7857,12655500\n2016-07-11,53.6049,10394366\n2016-07-12,54.7089,10998486\n2016-07-13,53.7572,12183638\n2016-07-14,54.8136,11353599\n2016-07-15,54.6423,8494000\n2016-07-18,54.1759,7614635\n2016-07-19,54.0237,8719772\n2016-07-20,54.7661,9446396\n2016-07-21,54.8232,16151699\n2016-07-22,55.1087,23899275\n2016-07-25,55.1563,10486019\n2016-07-26,55.4989,10106663\n2016-07-27,55.0611,6551777\n2016-07-28,55.4038,6830059\n2016-07-29,55.2515,6914907\n2016-08-01,54.8517,7997576\n2016-08-02,54.1831,7574622\n2016-08-03,53.4286,11484792\n2016-08-04,52.9319,11193748\n2016-08-05,53.3904,9206197\n2016-08-08,52.8746,9129307\n2016-08-09,52.7218,7136683\n2016-08-10,53.123,6991077\n2016-08-11,52.9797,6191412\n2016-08-12,52.9797,5039757\n2016-08-15,52.7696,5968728\n2016-08-16,52.8842,5751178\n2016-08-17,53.2949,7410631\n2016-08-18,53.037,5390990\n2016-08-19,52.4735,8981214\n2016-08-22,53.3426,8837808\n2016-08-23,53.8679,7827873\n2016-08-24,54.527,13200460\n2016-08-25,54.718,6686589\n2016-08-26,54.718,6940511\n2016-08-29,54.25,7026700\n2016-08-30,53.8679,6377668\n2016-08-31,53.7056,6996894\n2016-09-01,53.782,6230148\n2016-09-02,53.6578,7441463\n2016-09-06,53.505,6472907\n2016-09-07,53.7915,11428644\n2016-09-08,52.8173,12673626\n2016-09-09,51.91,10658120\n2016-09-12,52.2538,11002544\n2016-09-13,51.5566,10050215\n2016-09-14,51.4802,6707850\n2016-09-15,51.6807,8080426\n2016-09-16,51.3274,10207750\n2016-09-19,50.6301,9231628\n2016-09-20,50.9071,8731499\n2016-09-21,51.5566,9213637\n2016-09-22,51.9482,9096709\n2016-09-23,51.9864,6945147\n2016-09-26,51.6139,7755629\n2016-09-27,51.7572,6463747\n2016-09-28,51.5566,8593496\n2016-09-29,51.0504,11993517\n2016-09-30,51.7094,13767754\n2016-10-03,51.4229,5479037\n2016-10-04,51.1268,6176358\n2016-10-05,50.9549,7451916\n2016-10-06,50.7543,6130270\n2016-10-07,51.0599,7279723\n2016-10-10,50.9071,7224335\n2016-10-11,50.5442,9720407\n2016-10-12,50.7734,6320462\n2016-10-13,50.5728,6958128\n2016-10-14,50.697,6430136\n2016-10-17,50.3914,5223526\n2016-10-18,50.2481,6550399\n2016-10-19,50.7638,9095261\n2016-10-20,51.1841,9286800\n2016-10-21,51.2223,6767204\n2016-10-24,51.7476,6919714\n2016-10-25,51.2605,6052830\n2016-10-26,51.2223,5817798\n2016-10-27,51.1841,7899957\n2016-10-28,51.1268,6620333\n2016-10-31,50.6874,9142509\n2016-11-01,50.143,15425819\n2016-11-02,50.6015,10851658\n2016-11-03,49.4458,21847292\n2016-11-04,50.3818,21956848\n2016-11-07,52.0437,14916848\n2016-11-08,52.1678,9351994\n2016-11-09,52.1296,13727777\n2016-11-10,51.165,13621701\n2016-11-11,51.5088,8436435\n2016-11-14,51.7858,10489826\n2016-11-15,52.3807,9588036\n2016-11-16,53.1963,10779155\n2016-11-17,53.5897,8744504\n2016-11-18,53.513,8740953\n2016-11-21,53.8296,8004000\n2016-11-22,54.8083,10268720\n2016-11-23,55.2593,8183628\n2016-11-25,55.1058,3228848\n2016-11-28,55.2593,8750925\n2016-11-29,55.8158,10582850\n2016-11-30,55.6239,9527959\n2016-12-01,56.1421,12381607\n2016-12-02,54.8947,16869957\n2016-12-05,55.173,7701167\n2016-12-06,55.1154,7035674\n2016-12-07,56.382,9094812\n2016-12-08,56.2764,7972498\n2016-12-09,56.3724,7091577\n2016-12-12,56.3916,7736198\n2016-12-13,56.9097,8878080\n2016-12-14,56.3724,9022867\n2016-12-15,55.3745,11837756\n2016-12-16,55.3265,10611461\n2016-12-19,55.3169,6433824\n2016-12-20,55.3649,4888284\n2016-12-21,55.1154,5380537\n2016-12-22,54.7987,6777656\n2016-12-23,54.7028,4298476\n2016-12-27,54.5589,4186157\n2016-12-28,54.0695,5548726\n2016-12-29,54.0407,3781721\n2016-12-30,53.2731,8344508\n2017-01-03,53.11,7809307\n2017-01-04,53.7241,7796290\n2017-01-05,54.175,7602321\n2017-01-06,54.8179,8587812\n2017-01-09,55.8446,12640515\n2017-01-10,55.5376,6672024\n2017-01-11,55.7487,6027960\n2017-01-12,55.6815,4733015\n2017-01-13,55.5088,4745840\n2017-01-17,55.6527,5734666\n2017-01-18,56.0845,7375725\n2017-01-19,55.5472,7850480\n2017-01-20,55.3265,7651562\n2017-01-23,55.4224,6814368\n2017-01-24,56.0749,10704103\n2017-01-25,56.3244,7124547\n2017-01-26,56.0941,12382416\n2017-01-27,53.8488,28884899\n2017-01-30,53.6377,13322010\n2017-01-31,52.9852,14307985\n2017-02-01,51.7186,18796871\n2017-02-02,51.6899,15289650\n2017-02-03,52.8317,14161693\n2017-02-06,53.4746,13029829\n2017-02-07,53.2433,9910498\n2017-02-08,53.224,11681938\n2017-02-09,53.7927,11106757\n2017-02-10,54.1878,11178950\n2017-02-13,54.0818,8027939\n2017-02-14,54.5348,8865947\n2017-02-15,54.8047,6967179\n2017-02-16,54.6794,8524519\n2017-02-17,55.277,11008366\n2017-02-21,55.4601,8289185\n2017-02-22,55.489,7876599\n2017-02-23,55.5565,7178627\n2017-02-24,55.4023,7806190\n2017-02-27,54.7276,7702400\n2017-02-28,54.8143,8750655\n2017-03-01,55.0746,7197973\n2017-03-02,55.0553,6595418\n2017-03-03,55.036,7738064\n2017-03-06,54.6312,9159983\n2017-03-07,54.1686,10890313\n2017-03-08,53.7252,13061632\n2017-03-09,53.1951,17844248\n2017-03-10,52.5589,13886431\n2017-03-13,52.6553,9090230\n2017-03-14,52.3083,7892888\n2017-03-15,52.5686,8712006\n2017-03-16,52.8192,8074278\n2017-03-17,53.7637,15822141\n2017-03-20,53.7927,7948425\n2017-03-21,53.5324,8030642\n2017-03-22,53.8698,8452070\n2017-03-23,53.8312,7357207\n2017-03-24,54.7565,15763000\n2017-03-27,55.1613,8861799\n2017-03-28,55.277,8331644\n2017-03-29,55.4601,7001635\n2017-03-30,56.0577,8677916\n2017-03-31,56.2794,9156707\n2017-04-03,56.3276,8989831\n2017-04-04,56.2119,6474781\n2017-04-05,56.1155,13656221\n2017-04-06,55.8264,9112533\n2017-04-07,55.9228,6773750\n2017-04-10,55.8553,5266312\n2017-04-11,55.7878,5855091\n2017-04-12,55.4987,5450298\n2017-04-13,55.4312,4871717\n2017-04-17,55.9806,5626042\n2017-04-18,56.2409,5449699\n2017-04-19,56.9059,12000639\n2017-04-20,57.9083,12445862\n2017-04-21,58.4192,8799985\n2017-04-24,58.9011,10721276\n2017-04-25,58.7565,11031475\n2017-04-26,59.3348,8525419\n2017-04-27,59.0842,15285342\n2017-04-28,57.889,25046130\n2017-05-01,58.0047,10910341\n2017-05-02,58.3131,9152088\n2017-05-03,58.3999,7706367\n2017-05-04,58.6312,6874286\n2017-05-05,58.7469,6443309\n2017-05-08,58.7372,5588371\n2017-05-09,59.0179,5806562\n2017-05-10,58.7082,7198414\n2017-05-11,58.3307,5516893\n2017-05-12,58.0017,5647531\n2017-05-15,58.5049,5904094\n2017-05-16,58.0501,6303480\n2017-05-17,57.8081,7581230\n2017-05-18,57.8952,8602411\n2017-05-19,59.3856,12530995\n2017-05-22,59.2598,6392124\n2017-05-23,59.1824,5622524\n2017-05-24,59.8986,7283789\n2017-05-25,60.8761,8931804\n2017-05-26,61.2632,6097990\n2017-05-30,61.2245,7094586\n2017-05-31,61.5633,7314634\n2017-06-01,61.6987,6058263\n2017-06-02,62.4924,7840374\n2017-06-05,62.202,6809284\n2017-06-06,62.0956,5448439\n2017-06-07,61.4568,8364994\n2017-06-08,60.2373,11289266\n2017-06-09,60.1889,11240487\n2017-06-12,59.3179,11071593\n2017-06-13,58.9598,9384906\n2017-06-14,58.3307,9703332\n2017-06-15,58.1565,7515980\n2017-06-16,58.2049,11522438\n2017-06-19,58.9404,6778024\n2017-06-20,57.9339,6985666\n2017-06-21,58.0307,6027647\n2017-06-22,57.5952,5602002\n2017-06-23,57.8855,6469495\n2017-06-26,57.721,5674637\n2017-06-27,57.0629,5652429\n2017-06-28,57.2758,5419169\n2017-06-29,56.4822,7421177\n2017-06-30,56.4338,8117066\n2017-07-03,56.3757,4575268\n2017-07-05,56.0757,7773566\n2017-07-06,55.7466,8886648\n2017-07-07,56.1725,7278250\n2017-07-10,55.9499,4832094\n2017-07-11,56.037,5422330\n2017-07-12,56.6564,7141916\n2017-07-13,56.5015,8460245\n2017-07-14,56.8693,5441377\n2017-07-17,56.4531,6774471\n2017-07-18,56.337,7857464\n2017-07-19,56.2402,8203557\n2017-07-20,56.1628,10546701\n2017-07-21,56.1144,6717235\n2017-07-24,56.1531,7442589\n2017-07-25,56.6661,7933137\n2017-07-26,56.0757,8775889\n2017-07-27,57.5855,23286716\n2017-07-28,52.2625,53454789\n2017-07-31,52.2431,20299407\n2017-08-01,52.969,18120912\n2017-08-02,53.6465,14764854\n2017-08-03,53.8884,13331459\n2017-08-04,53.6561,9179779\n2017-08-07,53.84,7253947\n2017-08-08,53.0039,11095259\n2017-08-09,52.2456,16717719\n2017-08-10,51.5943,13235301\n2017-08-11,51.7012,9235033\n2017-08-14,51.7401,7426467\n2017-08-15,51.672,6674597\n2017-08-16,52.0123,7667081\n2017-08-17,51.5651,7451679\n2017-08-18,51.2345,10370499\n2017-08-21,51.672,12753196\n2017-08-22,52.9359,14547613\n2017-08-23,52.5762,11838533\n2017-08-24,52.4401,8716699\n2017-08-25,52.8484,8601120\n2017-08-28,52.8873,6643652\n2017-08-29,52.5956,6212403\n2017-08-30,53.0039,5596567\n2017-08-31,53.3345,8245287\n2017-09-01,53.4025,7696302\n2017-09-05,53.597,9178048\n2017-09-06,52.7998,11372298\n2017-09-07,51.9831,13801890\n2017-09-08,52.0026,11774483\n2017-09-11,52.5178,9314079\n2017-09-12,52.0512,10339446\n2017-09-13,52.7803,12787883\n2017-09-14,53.0137,8260770\n2017-09-15,53.1498,10744783\n2017-09-18,53.1692,6348360\n2017-09-19,53.1012,5187121\n2017-09-20,53.6164,7080035\n2017-09-21,53.4803,7178462\n2017-09-22,53.5581,6950029\n2017-09-25,53.422,10242655\n2017-09-26,53.597,8021851\n2017-09-27,53.4609,8671309\n2017-09-28,52.9845,7607473\n2017-09-29,52.2165,11944370\n2017-10-02,52.3137,5955980\n2017-10-03,52.4887,6137069\n2017-10-04,52.4303,5569058\n2017-10-05,53.0817,7994274\n2017-10-06,53.6359,10576278\n2017-10-09,53.49,5822893\n2017-10-10,53.8789,6573918\n2017-10-11,54.0928,8881897\n2017-10-12,54.4136,7234267\n2017-10-13,54.1706,6231132\n2017-10-16,53.3831,7256893\n2017-10-17,52.9942,11227337\n2017-10-18,53.6747,8299509\n2017-10-19,53.8595,5720179\n2017-10-20,53.0525,11741092\n2017-10-23,52.7609,10111071\n2017-10-24,52.7706,7818490\n2017-10-25,5

In [2]:
df = pd.read_csv('starbucks.csv', index_col='Date', parse_dates=True)
df.head()

              Close    Volume
Date
2015-01-02  38.0061   6906098
2015-01-05  37.2781  11623796
2015-01-06  36.9748   7664340
2015-01-07  37.8848   9732554
2015-01-08  38.4961  13170548

In [3]:
df.shift(1)

              Close      Volume
Date
2015-01-02      NaN         NaN
2015-01-05  38.0061   6906098.0
2015-01-06  37.2781  11623796.0
2015-01-07  36.9748   7664340.0
2015-01-08  37.8848   9732554.0
...             ...         ...
2018-12-24  61.3900  23524888.0
2018-12-26  60.5600   6323252.0
2018-12-27  63.0800  16646238.0
2018-12-28  63.2000  11308081.0
2018-12-31  63.3900   7712127.0

[1006 rows x 2 columns]

In [4]:
df.shift(-3)

              Close      Volume
Date
2015-01-02  37.8848   9732554.0
2015-01-05  38.4961  13170548.0
2015-01-06  37.2361  27556706.0
2015-01-07  37.4415  10021486.0
2015-01-08  37.7401  11040702.0
...             ...         ...
2018-12-24  63.3900   7712127.0
2018-12-26  64.4000   7690183.0
2018-12-27      NaN         NaN
2018-12-28      NaN         NaN
2018-12-31      NaN         NaN

[1006 rows x 2 columns]

In [5]:
 df.head()

              Close    Volume
Date
2015-01-02  38.0061   6906098
2015-01-05  37.2781  11623796
2015-01-06  36.9748   7664340
2015-01-07  37.8848   9732554
2015-01-08  38.4961  13170548

In [6]:
df.shift(periods=1, freq='M').head()

              Close    Volume
Date
2015-01-31  38.0061   6906098
2015-01-31  37.2781  11623796
2015-01-31  36.9748   7664340
2015-01-31  37.8848   9732554
2015-01-31  38.4961  13170548